### ISSUE TITLE
[0.7]Get a launch Crash 

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#10]
---- Minecraft Crash Report ----
// I blame PersonTheCat, author of Cave Generator.

Time: 2018-08-12 13:52:41 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cave Generator (cavegenerator)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at com.personthecat.cavegenerator.config.PresetReader.getMinNumber(PresetReader.java:660)
    at com.personthecat.cavegenerator.config.PresetReader.addFinalHeights(PresetReader.java:654)
    at com.personthecat.cavegenerator.config.PresetReader.setupGenerator(PresetReader.java:69)
    at com.personthecat.cavegenerator.config.PresetReader.<init>(PresetReader.java:49)
    at com.personthecat.cavegenerator.CaveInit.init(CaveInit.java:30)
    at com.personthecat.cavegenerator.Main.init(Main.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 116666176 bytes (111 MB) / 721420288 bytes (688 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2745 Optifine OptiFine_1.12.2_HD_U_E2 123 mods loaded, 123 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                       | Version                  | Source                                            | Signature                                |
       |:----- |:------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | UCHI  | minecraft                | 1.12.2                   | minecraft.jar                                     | None                                     |
       | UCHI  | mcp                      | 9.42                     | minecraft.jar                                     | None                                     |
       | UCHI  | FML                      | 8.0.99.99                | forge-1.12.2-14.23.4.2745.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | forge                    | 14.23.4.2745             | forge-1.12.2-14.23.4.2745.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | OpenEye                  | 0.8                      | OpenEye-1.12.2-0.8.jar                            | None                                     |
       | UCHI  | smoothfontcore           | 1.12.2-1.14              | minecraft.jar                                     | None                                     |
       | UCHI  | openmodscore             | 0.11.5                   | minecraft.jar                                     | None                                     |
       | UCHI  | foamfixcore              | 7.7.4                    | minecraft.jar                                     | None                                     |
       | UCHI  | elucore                  | 1.0                      | minecraft.jar                                     | None                                     |
       | UCHI  | smoothfont               | 1.12.2-1.15              | SmoothFont-1.12.2-1.15.jar                        | None                                     |
       | UCHI  | ucb                      | 0.3 Beta                 | [1.12.2]+UnderwaterChestBubbles_-0.3_Beta.jar     | None                                     |
       | UCHI  | movillages               | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                        | None                                     |
       | UCHI  | forgeendertech           | 1.12.2-4.3.20.1          | ForgeEndertech-1.12.2-4.3.20.1-build.0163.jar     | None                                     |
       | UCHI  | adhooks                  | 1.12.2-3.2.1.0           | AdHooks-1.12.2-3.2.1.0-build.0155.jar             | None                                     |
       | UCHI  | adpother                 | 1.12.2-0.8.0.1           | AdPother-1.12.2-0.8.0.1-build.0162.jar            | None                                     |
       | UCHI  | aiimprovements           | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                   | None                                     |
       | UCHI  | ambientsounds            | 2.0.0                    | AmbientSounds_v2.3_mc1.12.2.jar                   | None                                     |
       | UCHI  | antiqueatlas             | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHI  | antiqueatlasoverlay      | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHI  | examplemod               | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHI  | applecore                | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                      | None                                     |
       | UCHI  | charset                  | 0.5.4.7                  | Charset-Lib-0.5.4.7.jar                           | None                                     |
       | UCHI  | jei                      | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                         | None                                     |
       | UCHI  | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | UCHI  | aqueducts                | 0.2                      | Aqueducts-0.2.jar                                 | None                                     |
       | UCHI  | quark                    | r1.4-125                 | Quark-r1.4-125.jar                                | None                                     |
       | UCHI  | autoreglib               | 1.3-18                   | AutoRegLib-1.3-18.jar                             | None                                     |
       | UCHI  | babymobs                 | 1.5.5                    | BabyMobs-1.12-1.5.5.jar                           | None                                     |
       | UCHI  | backpacks16840           | 3.5.2                    | backpacks+1.12.2+-+3.5.2.jar                      | None                                     |
       | UCHI  | backups                  | 1.3                      | Backups-1.12.2-1.3.jar                            | None                                     |
       | UCHI  | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | UCHI  | baubleofundying          | 1.0.1                    | BaubleOfUndying-1.12-1.0.1.jar                    | None                                     |
       | UCHI  | bettercombatmod          | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                     | None                                     |
       | UCHI  | betterfoliage            | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                   | None                                     |
       | UCHI  | betteroffhand            | 0.2                      | betteroffhand-1.12.2-0.2.jar                      | None                                     |
       | UCHI  | betterplacement          | 1.0.0-1                  | BetterPlacement-1.0.0-1.jar                       | None                                     |
       | UCHI  | betterunderground        | 1.1.7                    | betterunderground_1.12.2_1.1.7.jar                | None                                     |
       | UCHI  | blockcraftery            | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
       | UCHI  | bloodmoon                | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHI  | blur                     | 1.0.4-14                 | Blur-1.0.4-14.jar                                 | None                                     |
       | UCHEE | cavegenerator            | 0.7                      | cavegenerator-0.7.jar                             | None                                     |
       | UCH   | chopdownupdated          | 1.1.1                    | ChopDown+Updated+(1.12.2+)-1.1.1.jar              | None                                     |
       | UCH   | clumps                   | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
       | UCH   | colytra                  | 1.1.0                    | colytra-1.12.2-1.1.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCH   | potioncore               | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                     | None                                     |
       | UCH   | compot                   | 1.1                      | CombinedPotions-1.12-1.1.jar                      | None                                     |
       | UCH   | compasscoords            | 1.12-3.3.2               | CompassCoords-1.12-3.3.2.jar                      | None                                     |
       | UCH   | controlling              | 3.0.6                    | Controlling-3.0.6.jar                             | None                                     |
       | UCH   | craftingautomat          | 1.0.3                    | CraftingAutomat-MC1.12.2-1.0.3.jar                | None                                     |
       | UCH   | craftingex               | 1.2.0                    | CraftingEX_1.12-v1.2.0.jar                        | None                                     |
       | UCH   | crafttweaker             | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCH   | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCH   | crafttweakerjei          | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCH   | forgecreeperheal         | 1.3.0                    | creeperheal-1.12-1.3.1.jar                        | None                                     |
       | UCH   | ctm                      | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
       | UCH   | custombackgrounds        | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar                | None                                     |
       | UCH   | damagemark               | 1.4                      | DamageMarkMod-1.12.2-1.4.jar                      | None                                     |
       | UCH   | dungpipe                 | 1.0                      | Dung+Pipe-1.2.jar                                 | None                                     |
       | UCH   | durabilityshow           | 5.0.0                    | Durability+Show-1.12-5.0.0.jar                    | None                                     |
       | UCH   | emberroot                | 1.3.9                    | EmberRootZoo-1.12.2-1.3.9.jar                     | None                                     |
       | UCH   | csb_ench_table           | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                    | None                                     |
       | UCH   | enhanced_snowman         | 1.0                      | EnhancedSnowman-1.12-1.0.1.jar                    | None                                     |
       | UCH   | explodingmobs            | v1.4                     | ExplodingMobs-1.12.2-1.4.jar                      | None                                     |
       | UCH   | extraalchemy             | 0.3.8.5-release          | extraalchemy-0.3.8.5-release.jar                  | None                                     |
       | UCH   | fbp                      | 2.4.0                    | FancyBlockParticles-1.12.x-2.4.0.jar              | None                                     |
       | UCH   | ffenchants               | 1.0                      | ffe-1.12.2-1.0.jar                                | None                                     |
       | UCH   | flowstone                | 1                        | flowstone-1.0.jar                                 | None                                     |
       | UCH   | foamfix                  | 0.10.0-1.12.2            | foamfix-0.10.0-1.12.2.jar                         | None                                     |
       | UCH   | friendshipbracelet       | 1.1.2                    | FriendshipBracelet-1.1.2.jar                      | None                                     |
       | UCH   | giacomos_teleport        | 1.3                      | GiacomosTeleport-1.12.2-1.3.jar                   | None                                     |
       | UCH   | increasemobs             | 1.1.0                    | IncreaseMobs_1.12.2-v1.1.0.jar                    | None                                     |
       | UCH   | infernalmobs             | 1.7.5                    | InfernalMobs-1.12.2.jar                           | None                                     |
       | UCH   | mantle                   | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                          | None                                     |
       | UCH   | inspirations             | 1.12.2-0.2.1             | Inspirations-1.12.2-0.2.1.jar                     | None                                     |
       | UCH   | inventoryspam            | 1.0.3                    | InventorySpam-1.12.0-1.0.3.jar                    | None                                     |
       | UCH   | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCH   | itemscroller             | 0.12.0                   | itemscroller-1.12.2-0.12.0.jar                    | 2b03e1423915a189b8094816baa18f239d576dff |
       | UCH   | jaff                     | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
       | UCH   | loottweaker              | 0.0.7                    | LootTweaker-1.12.2-0.0.7.jar                      | None                                     |
       | UCH   | jeresources              | 0.8.9.48                 | JustEnoughResources-1.12.2-0.8.9.48.jar           | None                                     |
       | UCH   | kleeslabs                | 5.4.10                   | KleeSlabs_1.12.2-5.4.10.jar                       | None                                     |
       | UCH   | kc                       | 1.12                     | knobcontrol-1.12-4.0.20.jar                       | None                                     |
       | UCH   | linear                   | 1.1                      | Linear+MC1.12.2+v1.1.jar                          | None                                     |
       | UCH   | magma_monsters           | 0.3.0                    | MagmaMonsters-0.3.0.jar                           | None                                     |
       | UCH   | makezoomzoom             | 0.0.4                    | MakeZoomZoom-0.0.4.jar                            | None                                     |
       | UCH   | menumobs                 | 1.21                     | MenuMobs-1.12.2-1.21.jar                          | None                                     |
       | UCH   | mobspropertiesrandomness | 1.3.3                    | MobsPropertiesRandomness-1.3.3-mc1.12.x.jar       | None                                     |
       | UCH   | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
       | UCH   | neat                     | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
       | UCH   | oreexcavation            | 1.4.119                  | OreExcavation-1.4.119.jar                         | None                                     |
       | UCH   | oeintegration            | 2.3.3                    | oeintegration-2.3.3.jar                           | None                                     |
       | UCH   | oops                     | @VERSION@                | oops-1.12-5.11.jar                                | None                                     |
       | UCH   | openmods                 | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCH   | openblocks               | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCH   | ore_stone_variants       | 3.7                      | ore_stone_variants-3.7.jar                        | None                                     |
       | UCH   | overpoweredarmorbar      | 0.2.1                    | overpoweredarmorbar-1.12.2-0.2.1.jar              | None                                     |
       | UCH   | palimpsest               | 1.2.3                    | palimpsest-1.12.2-1.2.3.jar                       | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | UCH   | pantography              | 1.3.0                    | pantography-1.12.2-1.3.0.jar                      | None                                     |
       | UCH   | potioncraft              | 1.1.1                    | potioncraft-1.1.1.jar                             | None                                     |
       | UCH   | primitivemobs            | 1.1.6                    | primitivemobs-1.1.6_beta.jar                      | None                                     |
       | UCH   | pvj                      | 1.0.1                    | ProjectVibrantJourneys-1.12.2-1.0.1.jar           | None                                     |
       | UCH   | pdp                      | 1.12.2-1.1.0             | ProportionalDestructionParticles-1.12.2-1.1.0.jar | None                                     |
       | UCH   | pyramidplunder           | 1.12.2-1.0               | PyramidPlunder-1.12.2-1.0.jar                     | None                                     |
       | UCH   | qualitytools             | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar                 | None                                     |
       | UCH   | randomtweaks             | 1.12.2-2.1.2.2           | randomtweaks-1.12.2-2.1.2.2.jar                   | None                                     |
       | UCH   | redstonepaste            | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | UCH   | rockycore                | 0.4.0                    | rockycore-1.12.2-0.4.0.jar                        | None                                     |
       | UCH   | ruins                    | 16.9                     | Ruins-1.12.jar                                    | None                                     |
       | UCH   | schematics               | 1.12.2.11                | Schematics-1.12.2.11.jar                          | None                                     |
       | UCH   | sereneseasons            | 1.2.5                    | SereneSeasons-1.12.2-1.2.5-universal.jar          | None                                     |
       | UCH   | solcarrot                | 1.3.1                    | solcarrot-1.12.2-1.3.3.jar                        | None                                     |
       | UCH   | soundfilters             | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                    | None                                     |
       | UCH   | spartanshields           | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                   | None                                     |
       | UCH   | stg                      | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
       | UCH   | survivaltweaks           | 5.1.0                    | SurvivalTweaks-5.1.0-1.12.2.jar                   | None                                     |
       | UCH   | theoneprobe              | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                       | None                                     |
       | UCH   | thrownslime              | 1.2.1                    | thrownslime-1.12.2-1.3.0.jar                      | None                                     |
       | UCH   | tipline                  | 1.0.4                    | tipline-1.12-1.0.4.jar                            | None                                     |
       | UCH   | toolbelt                 | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                         | None                                     |
       | UCH   | va                       | 1.12.2-1.5.3             | va-1.12.2-1.5.4.jar                               | None                                     |
       | UCH   | vanillafix               | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                           | None                                     |
       | UCH   | wts                      | 1.1.0                    | WTS-1.1.0.jar                                     | None                                     |
       | UCH   | elulib                   | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.0-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MZZLoadingPlugin (MakeZoomZoom-0.0.4.jar)
                                        xyz.ajp.makezoomzoom.asm.MZZClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                        openeye.asm.MultiTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.5-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.3.20.1-build.0163.jar)
                                        
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FMLPlugin (elulib-0.1.12.jar)
                                        elucent.elulib.asm.ASMTransformer
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      LoadingPlugin (AdPother-1.12.2-0.8.0.1-build.0162.jar)
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
                                        com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
                                        com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
                                        com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
                                        com.endertech.minecraft.mods.adpother.renders.AerometerRender
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                        openmods.core.OpenModsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      IonChests (IonChests-1.0.0.jar)
                                        pl.asie.ionchests.IonChestsTransformer
                                      CorePlugin (SmoothFont-1.12.2-1.15.jar)
                                        bre.smoothfont.asm.Transformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
                                        com.chocohead.biab.BornInABarn
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Quark-r1.4-125.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      No More Glowing Pots (nomoreglowingpots-1.0.jar)
                                        zabi.minecraft.nomoreglowingpots.PotionTransformer
                                      ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
                                        brad16840.core.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4889' Renderer: 'Intel(R) HD Graphics 4600'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - TheOneProbePlugin (Enabled/Not Forced)
  Suspected Mods: Cave Generator (cavegenerator)
  Launched Version: HMCL 3.1.64
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.14.4889, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 3D+1+Day+Seasons+Changing+by+creatorLabs+-+V1.0.0.1.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz

**Comment by PersonTheCat** [comment]
Sorry, I didn't expect this to happen. I'll fix it right away. Thanks!

**Comment by PersonTheCat** [comment]
Just uploaded the fix. Was able to quickly reproduce the issue and verify that the new build is working just fine. Sorry about that! Let me know if everything is working for you when it's out.

Thanks again!

**Comment by Knito58** [comment]
This was a fast reporting and a fast fix! Wanted to report the exactly same error just to see it is already fixed. Thanks guys!

**Comment by PersonTheCat** [comment]
Awesome! I'm glad to hear that. Unlike a lot of bugs, this was a pretty dumb mistake, honestly. Let me know if you have any other issues.

**Comment by Knito58** [comment]
:)
