### ISSUE TITLE
[0.9]Crash in world generation

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#12]
---- Minecraft Crash Report ----
// I blame PersonTheCat, author of Cave Generator.

Time: 2018-08-19 17:32:34 CST
Description: Exception in server tick loop

java.lang.NullPointerException
    at com.personthecat.cavegenerator.world.feature.CaveFeatureGenerator.generate(CaveFeatureGenerator.java:29)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1018)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:997)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:186)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:209)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1562746576 bytes (1490 MB) / 2164260864 bytes (2064 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.4.2747 Optifine OptiFine_1.12.2_HD_U_E2 123 mods loaded, 123 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State   | ID                       | Version                  | Source                                            | Signature                                |
       |:------- |:------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | UCHIJAA | minecraft                | 1.12.2                   | minecraft.jar                                     | None                                     |
       | UCHIJAA | mcp                      | 9.42                     | minecraft.jar                                     | None                                     |
       | UCHIJAA | FML                      | 8.0.99.99                | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAA | forge                    | 14.23.4.2747             | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAA | OpenEye                  | 0.8                      | OpenEye-1.12.2-0.8.jar                            | None                                     |
       | UCHIJAA | smoothfontcore           | 1.12.2-1.14              | minecraft.jar                                     | None                                     |
       | UCHIJAA | openmodscore             | 0.11.5                   | minecraft.jar                                     | None                                     |
       | UCHIJAA | foamfixcore              | 7.7.4                    | minecraft.jar                                     | None                                     |
       | UCHIJAA | randompatches            | 1.12.2-1.4.1.1           | randompatches-1.12.2-1.4.1.1.jar                  | None                                     |
       | UCHIJAA | elucore                  | 1.0                      | minecraft.jar                                     | None                                     |
       | UCHIJAA | smoothfont               | 1.12.2-1.15              | SmoothFont-1.12.2-1.15.jar                        | None                                     |
       | UCHIJAA | ucb                      | 0.3 Beta                 | [1.12.2]+UnderwaterChestBubbles_-0.3_Beta.jar     | None                                     |
       | UCHIJAA | movillages               | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                        | None                                     |
       | UCHIJAA | aiimprovements           | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                   | None                                     |
       | UCHIJAA | ambientsounds            | 2.0.0                    | AmbientSounds_v2.3_mc1.12.2.jar                   | None                                     |
       | UCHIJAA | antiqueatlas             | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHIJAA | antiqueatlasoverlay      | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHIJAA | examplemod               | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | UCHIJAA | applecore                | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                      | None                                     |
       | UCHIJAA | charset                  | 0.5.5.1                  | Charset-Lib-0.5.5.1.jar                           | None                                     |
       | UCHIJAA | jei                      | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                         | None                                     |
       | UCHIJAA | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | UCHIJAA | aqueducts                | 0.2                      | Aqueducts-0.2.jar                                 | None                                     |
       | UCHIJAA | quark                    | r1.5-127                 | Quark-r1.5-127.jar                                | None                                     |
       | UCHIJAA | autoreglib               | 1.3-20                   | AutoRegLib-1.3-20.jar                             | None                                     |
       | UCHIJAA | babymobs                 | 1.5.5                    | BabyMobs-1.12-1.5.5.jar                           | None                                     |
       | UCHIJAA | backpacks16840           | 3.5.2                    | backpacks+1.12.2+-+3.5.2.jar                      | None                                     |
       | UCHIJAA | backups                  | 1.3                      | Backups-1.12.2-1.3.jar                            | None                                     |
       | UCHIJAA | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | UCHIJAA | baubleofundying          | 1.0.1                    | BaubleOfUndying-1.12-1.0.1.jar                    | None                                     |
       | UCHIJAA | miscrails                | 1.0.0                    | Better-Railroads-1.0.0.jar                        | None                                     |
       | UCHIJAA | bettercombatmod          | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                     | None                                     |
       | UCHIJAA | betterfoliage            | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                   | None                                     |
       | UCHIJAA | betteroffhand            | 0.2                      | betteroffhand-1.12.2-0.2.jar                      | None                                     |
       | UCHIJAA | betterplacement          | 1.0.0-1                  | BetterPlacement-1.0.0-1.jar                       | None                                     |
       | UCHIJAA | blockcraftery            | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
       | UCHIJAA | bloodmoon                | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAA | blur                     | 1.0.4-14                 | Blur-1.0.4-14.jar                                 | None                                     |
       | UCHIJAA | cavegenerator            | 0.9                      | cavegenerator-0.9.jar                             | None                                     |
       | UCHIJAA | chopdownupdated          | 1.1.1                    | ChopDown+Updated+(1.12.2+)-1.1.1.jar              | None                                     |
       | UCHIJAA | clumps                   | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
       | UCHIJAA | colytra                  | 1.1.0                    | colytra-1.12.2-1.1.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJAA | potioncore               | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                     | None                                     |
       | UCHIJAA | compot                   | 1.1                      | CombinedPotions-1.12-1.1.jar                      | None                                     |
       | UCHIJAA | compasscoords            | 1.12-3.3.2               | CompassCoords-1.12-3.3.2.jar                      | None                                     |
       | UCHIJAA | controlling              | 3.0.6                    | Controlling-3.0.6.jar                             | None                                     |
       | UCHIJAA | craftingautomat          | 1.0.3                    | CraftingAutomat-MC1.12.2-1.0.3.jar                | None                                     |
       | UCHIJAA | crafttweaker             | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCHIJAA | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCHIJAA | crafttweakerjei          | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
       | UCHIJAA | forgecreeperheal         | 1.3.0                    | creeperheal-1.12-1.3.1.jar                        | None                                     |
       | UCHIJAA | ctm                      | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
       | UCHIJAA | custombackgrounds        | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar                | None                                     |
       | UCHIJAA | damagemark               | 1.4                      | DamageMarkMod-1.12.2-1.4.jar                      | None                                     |
       | UCHIJAA | dungpipe                 | 1.0                      | Dung+Pipe-1.2.jar                                 | None                                     |
       | UCHIJAA | durabilityshow           | 5.0.0                    | Durability+Show-1.12-5.0.0.jar                    | None                                     |
       | UCHIJAA | emberroot                | 1.3.9                    | EmberRootZoo-1.12.2-1.3.9.jar                     | None                                     |
       | UCHIJAA | csb_ench_table           | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                    | None                                     |
       | UCHIJAA | enhanced_snowman         | 1.0                      | EnhancedSnowman-1.12-1.0.1.jar                    | None                                     |
       | UCHIJAA | explodingmobs            | v1.4                     | ExplodingMobs-1.12.2-1.4.jar                      | None                                     |
       | UCHIJAA | extraalchemy             | 0.3.8.5-release          | extraalchemy-0.3.8.5-release.jar                  | None                                     |
       | UCHIJAA | fbp                      | 2.4.0                    | FancyBlockParticles-1.12.x-2.4.0.jar              | None                                     |
       | UCHIJAA | ffenchants               | 1.0                      | ffe-1.12.2-1.0.jar                                | None                                     |
       | UCHIJAA | flowstone                | 1                        | flowstone-1.0.jar                                 | None                                     |
       | UCHIJAA | foamfix                  | 0.10.0-1.12.2            | foamfix-0.10.0-1.12.2.jar                         | None                                     |
       | UCHIJAA | friendshipbracelet       | 1.1.2                    | FriendshipBracelet-1.1.2.jar                      | None                                     |
       | UCHIJAA | giacomos_teleport        | 1.3                      | GiacomosTeleport-1.12.2-1.3.jar                   | None                                     |
       | UCHIJAA | i18nmod                  | 1.12.2-1.0.6             | i18nupdatemod-1.12.2-1.0.6.jar                    | None                                     |
       | UCHIJAA | increasemobs             | 1.1.0                    | IncreaseMobs_1.12.2-v1.1.0.jar                    | None                                     |
       | UCHIJAA | infernalmobs             | 1.7.5                    | InfernalMobs-1.12.2.jar                           | None                                     |
       | UCHIJAA | mantle                   | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                          | None                                     |
       | UCHIJAA | inspirations             | 1.12.2-0.2.1             | Inspirations-1.12.2-0.2.1.jar                     | None                                     |
       | UCHIJAA | inventoryspam            | 1.0.3                    | InventorySpam-1.12.0-1.0.3.jar                    | None                                     |
       | UCHIJAA | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAA | itemscroller             | 0.12.0                   | itemscroller-1.12.2-0.12.0.jar                    | 2b03e1423915a189b8094816baa18f239d576dff |
       | UCHIJAA | jaff                     | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
       | UCHIJAA | loottweaker              | 0.0.7                    | LootTweaker-1.12.2-0.0.7.jar                      | None                                     |
       | UCHIJAA | jeresources              | 0.8.9.48                 | JustEnoughResources-1.12.2-0.8.9.48.jar           | None                                     |
       | UCHIJAA | kleeslabs                | 5.4.10                   | KleeSlabs_1.12.2-5.4.10.jar                       | None                                     |
       | UCHIJAA | kc                       | 1.12                     | knobcontrol-1.12-4.0.20.jar                       | None                                     |
       | UCHIJAA | linear                   | 1.1                      | Linear+MC1.12.2+v1.1.jar                          | None                                     |
       | UCHIJAA | magma_monsters           | 0.3.0                    | MagmaMonsters-0.3.0.jar                           | None                                     |
       | UCHIJAA | makezoomzoom             | 0.0.4                    | MakeZoomZoom-0.0.4.jar                            | None                                     |
       | UCHIJAA | menumobs                 | 1.21                     | MenuMobs-1.12.2-1.21.jar                          | None                                     |
       | UCHIJAA | mobspropertiesrandomness | 1.3.3                    | MobsPropertiesRandomness-1.3.3-mc1.12.x.jar       | None                                     |
       | UCHIJAA | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
       | UCHIJAA | neat                     | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
       | UCHIJAA | oreexcavation            | 1.4.119                  | OreExcavation-1.4.119.jar                         | None                                     |
       | UCHIJAA | oeintegration            | 2.3.3                    | oeintegration-2.3.3.jar                           | None                                     |
       | UCHIJAA | oops                     | @VERSION@                | oops-1.12-5.11.jar                                | None                                     |
       | UCHIJAA | openmods                 | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAA | openblocks               | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAA | ore_stone_variants       | 3.7                      | ore_stone_variants-3.7.jar                        | None                                     |
       | UCHIJAA | overpoweredarmorbar      | 0.2.1                    | overpoweredarmorbar-1.12.2-0.2.1.jar              | None                                     |
       | UCHIJAA | palimpsest               | 1.2.3                    | palimpsest-1.12.2-1.2.3.jar                       | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | UCHIJAA | pantography              | 1.3.0                    | pantography-1.12.2-1.3.0.jar                      | None                                     |
       | UCHIJAA | potioncraft              | 1.1.1                    | potioncraft-1.1.1.jar                             | None                                     |
       | UCHIJAA | primitivemobs            | 1.1.6                    | primitivemobs-1.1.6_beta.jar                      | None                                     |
       | UCHIJAA | pdp                      | 1.12.2-1.1.0             | ProportionalDestructionParticles-1.12.2-1.1.0.jar | None                                     |
       | UCHIJAA | pyramidplunder           | 1.12.2-1.0               | PyramidPlunder-1.12.2-1.0.jar                     | None                                     |
       | UCHIJAA | qualitytools             | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar                 | None                                     |
       | UCHIJAA | randomtweaks             | 1.12.2-2.1.2.2           | randomtweaks-1.12.2-2.1.2.2.jar                   | None                                     |
       | UCHIJAA | sandro                   | 1.3 BETA-2               | Redstone+++ver1.3+BETA-2.jar                      | None                                     |
       | UCHIJAA | redstoneplusplus         | 1.3 BETA-2               | Redstone+++ver1.3+BETA-2.jar                      | None                                     |
       | UCHIJAA | redstonepaste            | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | UCHIJAA | rockycore                | 0.4.0                    | rockycore-1.12.2-0.4.0.jar                        | None                                     |
       | UCHIJAA | ruins                    | 16.9                     | Ruins-1.12.jar                                    | None                                     |
       | UCHIJAA | schematics               | 1.12.2.12                | Schematics-1.12.2.12.jar                          | None                                     |
       | UCHIJAA | sereneseasons            | 1.2.5                    | SereneSeasons-1.12.2-1.2.5-universal.jar          | None                                     |
       | UCHIJAA | solcarrot                | 1.3.1                    | solcarrot-1.12.2-1.3.3.jar                        | None                                     |
       | UCHIJAA | soundfilters             | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                    | None                                     |
       | UCHIJAA | spartanshields           | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                   | None                                     |
       | UCHIJAA | stg                      | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
       | UCHIJAA | survivaltweaks           | 5.1.0                    | SurvivalTweaks-5.1.0-1.12.2.jar                   | None                                     |
       | UCHIJAA | theoneprobe              | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                       | None                                     |
       | UCHIJAA | thrownslime              | 1.2.1                    | thrownslime-1.12.2-1.3.0.jar                      | None                                     |
       | UCHIJAA | tipline                  | 1.0.4                    | tipline-1.12-1.0.4.jar                            | None                                     |
       | UCHIJAA | toolbelt                 | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                         | None                                     |
       | UCHIJAA | va                       | 1.12.2-1.5.3             | va-1.12.2-1.5.4.jar                               | None                                     |
       | UCHIJAA | vanillafix               | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                           | None                                     |
       | UCHIJAA | wts                      | 1.1.0                    | WTS-1.1.0.jar                                     | None                                     |
       | UCHIJAA | elulib                   | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |
       | UCHIJAA | pvj                      | 1.1.5                    | ProjectVibrantJourneys-1.12.2-1.1.5.jar           | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.0-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MZZLoadingPlugin (MakeZoomZoom-0.0.4.jar)
                                        xyz.ajp.makezoomzoom.asm.MZZClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                        openeye.asm.MultiTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.5-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                        openmods.core.OpenModsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      IonChests (IonChests-1.0.0.jar)
                                        pl.asie.ionchests.IonChestsTransformer
                                      CorePlugin (SmoothFont-1.12.2-1.15.jar)
                                        bre.smoothfont.asm.Transformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.4.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FMLPlugin (elulib-0.1.12.jar)
                                        elucent.elulib.asm.ASMTransformer
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
                                        com.chocohead.biab.BornInABarn
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Quark-r1.5-127.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      No More Glowing Pots (nomoreglowingpots-1.0.jar)
                                        zabi.minecraft.nomoreglowingpots.PotionTransformer
                                      ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
                                        brad16840.core.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - TheOneProbePlugin (Enabled/Not Forced)
  Suspected Mods: Cave Generator (cavegenerator)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Knito58** [comment]
Same. https://pastebin.com/ejPQJASs

**Comment by pirone2** [comment]
same

**Comment by PersonTheCat** [comment]
Damn. I guess I forgot to initialize a variable. I'll get that patch out in a minute. Thanks, guys.

**Comment by zzzqh** [comment]
Thanks, no longer crash in new version
