### ISSUE TITLE
( 0.14 ) Chunk related crash when loading a new world

### ISSUE THREAD

**Issue by Null-151** [PersonTheCat/CaveGenerator#19]
Im not sure if this crash is recreatable, since it only happened once during my testing
https://paste.dimdev.org/apavuwadat.mccrash

**Comment by PersonTheCat** [comment]
Hi, there. I'm not so convinced this problem is on my end. The only thing Cave Generator has done in this stacktrace is poll the World object for its current biome. You might have better luck asking the Climate Control devs.
