### ISSUE TITLE
Floating Vanilla Structures

### ISSUE THREAD

**Issue by CREEATION** [PersonTheCat/CaveGenerator#21]
Is there a way to prevent this from happening?

![2019-04-12_04 34 12](https://user-images.githubusercontent.com/3277769/56008572-e8372780-5cdc-11e9-8284-c7a09a22d685.png)

I didn't come up with a solution yet, not sure if it's possible to prevent.

**Comment by PersonTheCat** [comment]
Sadly, no. You would need a custom world generator that can handle spawning mineshafts on its own. I agree that they look bad, but have no way to fix it.
