### ISSUE TITLE
[0.16]About euclids tunnels

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#25]
1.Using euclids tunnels preset and found some strange wall in cave, I havn't seem it in 0.15 version when using the same preset.

https://github.com/zzzqh/justreport/blob/master/2019-08-26_12.46.35.png
https://github.com/zzzqh/justreport/blob/master/2019-08-26_12.46.42.png
https://github.com/zzzqh/justreport/blob/master/2019-08-26_12.46.45.png

2.Euclids tunnels will generate some one block tall room at the start and end of the cave,I think it is unfriently for explorer, is anyway to prevent?

**Comment by PersonTheCat** [comment]
Super duper old issue. Sorry for never responding. I believe we discussed this on Discord some time ago. In any case, the answer is ultimately no. There are ways to artificially stretch these caverns, but I don't think any are worth implementing at this point.
