### ISSUE TITLE
In-game config doesn't work

### ISSUE THREAD

**Issue by yungnickyoung** [PersonTheCat/CaveGenerator#26]
I only took a brief look at your code, so my apologies if this is incorrect, but it appears you don't actually have the in-game config hooked up to the config file. Changing the config in-game doesn't seem to do anything. You would need to subscribe a `ConfigChangedEvent.OnConfigChangedEvent` to the `EVENT_BUS` on the client side, like so:
```java
public static void onConfigReload(ConfigChangedEvent.OnConfigChangedEvent event) {
    // Only mess with config syncing if it is this mod being changed
    if ("cavegenerator".equals(event.getModID()))
        ConfigManager.sync("cavegenerator", Config.Type.INSTANCE);
}
```

**Comment by PersonTheCat** [comment]
Sorry about that. I figured that since the majority of configuration takes place outside of the game for this mod, adding in-game options for a few things wouldn't matter much. I can definitely add it in the next update, though.

**Comment by yungnickyoung** [comment]
Well, I noticed this in the first place because I made a cave mod similar to Worley's and people have asked me about compatibility. I would greatly appreciate the addition to avoid any confused people asking me why my caves still don't work with yours! If you need a reference on what to do (you probably don't given the complexity of your code, lol) check out my repo. It's a pretty straightforward addition.

Btw - just wanted to say, spectacular mod. I didn't know about this when I created my cave mod, but I sure wish I had. Its complexity and versatility is really astounding!

**Comment by PersonTheCat** [comment]
Sure thing! It's no big deal. Give me a bit to make sure I don't need to finish anything else before releasing an update soon. I'm mostly working on my other mod at the moment and don't even remember what I was doing with this one last I worked on it. 

Anyway, it looks like we have some very similar goals in mind with our projects. I'd love to offer some help with yours sometime, if needed and I have the time. I would also love any suggestions you can offer about Cave Generator. It seems quite a bit more tedious than yours and I think your feedback would be especially meaningful, considering that. Let me know!

**Comment by yungnickyoung** [comment]
That sounds great! I imagine we both have some good ideas and insights to make these mods as enjoyable as possible. If you use discord, shoot me a friend request at YUNGNICKYOUNG#7023.

**Comment by PersonTheCat** [comment]
This is a crazy old issue, but I believe this was fixed a while ago. Guess I'll close it! Thanks again.
