### ISSUE TITLE
Example presets override Bedrock @ y 0

### ISSUE THREAD

**Issue by Rongmario** [PersonTheCat/CaveGenerator#29]
This is with all exampled presets on except for `stone_layers`.

![2021-05-20_15 13 59](https://user-images.githubusercontent.com/3684700/118994538-564f7d80-b97e-11eb-854f-8367ab100e63.png)

**Comment by PersonTheCat** [comment]
Just a quick heads up: I don't recommend running all of the examples at the same time. Those are mostly intended for users to see how certain features are written. Is there any way you can identify a specific preset that causes this issue by itself? If not, I can take a look at it in a few weeks after I'm done with these next couple OSV updates.

**Comment by Rongmario** [comment]
Sure, I'll try to single out the preset.

**Comment by PersonTheCat** [comment]
Thanks for your help!

**Comment by Rongmario** [comment]
Seems to be:

- `cat`
- `cat_lite`
- `ore_veins`
- `stone_clusters`

**Comment by PersonTheCat** [comment]
Alright, thanks. I can take a look at this in a few days.

**Comment by PersonTheCat** [comment]
Hey, sorry it took so long. Just finished the OSV update that came before this. Working on this issue now. It's the only bug report I have, so it should only take a day or so.

**Comment by PersonTheCat** [comment]
Got it. It wound up being pretty much a code bug. Wound up fixing that and also porting over some improvements to `/cave backup` from OSV. I'll have that out in a minute.

**Comment by Rongmario** [comment]
Nice. Will take a look.

**Comment by PersonTheCat** [comment]
Gonna go ahead and close this issue. Feel free to open it back up if you run into issues again in the future.
