### ISSUE TITLE
JSON invalid in preset files

### ISSUE THREAD

**Issue by ScottoMotto** [PersonTheCat/CaveGenerator#3]
Attached is an archive with corrected versions.

Misspelling of "extensions"
Invalid "=" in minHeight and maxHeight

[cavegeneratorPresetsJSONFix.zip](https://github.com/PersonTheCat/CaveGenerator/files/2236933/cavegeneratorPresetsJSONFix.zip)

**Comment by PersonTheCat** [comment]
Thanks again. I have actually corrected these issues in my development build. That will be included in the next release.

**Comment by ScottoMotto** [comment]
Are inline comments meant to be formatted like:
"//" : "Options for these are 'vanilla_branches,' 'matching_branches,' 'preset:other_preset_name_here,' and 'room,'", 

That is how some are now.

**Comment by PersonTheCat** [comment]
Yeah, there's not really a good way to leave comments in json files. I may start a new format at some point, but not yet.

**Comment by ScottoMotto** [comment]
Ok, just learning the convention.

**Comment by PersonTheCat** [comment]
Just letting you know that I've uploaded a fix with the latest version. I'm gonna go ahead and close this.
