### ISSUE TITLE
height selectors do nothing?

### ISSUE THREAD

**Issue by Efimero** [PersonTheCat/CaveGenerator#4]
it seems like "minHeight" and "maxHeight" do nothing, but maybe I am doing something wrong?

ravines.json
```
{
  "chance": 100.0,
  "minHeight": 180,
  "maxHeight": 200,
	"scale" :
	{
		"exponent" : 1.0,
		"factor" : 1.0,
		"randomnessFactor" : 0.0,
		"startingValue" : 3.0,
		"startingValueRandomnessFactor" : 0.0
	},
	"scaleY" :
	{
		"exponent" : 1.0,
		"factor" : 1.0,
		"randomnessFactor" : 0.0,
		"startingValue" : 5.0
	},
	"slopeXZ" :
	{
		"startingValue" : 0.0,
		"startingValueRandomnessFactor" : 0.0
	},
	"slopeY" :
	{
    "randomnessFactor" : 0.0,
		"startingValue" : 0.0,
		"startingValueRandomnessFactor" : 0.0
	}
}
```
these appear at height 80 no matter what =/

**Comment by PersonTheCat** [comment]
So, I actually left myself a note to go back and improve this. The way it works in vanilla multiplies the value by 0-1 twice randomly, meaning that the actual min and max height are effectively much lower. I just need to figure out how to change that without breaking seeds in vanilla. Sorry about that! I'll get it working before 0.4.

**Comment by PersonTheCat** [comment]
This is no longer applicable as of version 0.13.

**Comment by zzzqh** [comment]
In 0.15 version, height limiter seems work wrong again
_{
  enabled: true
  ravines: {
     # Increase ravine frequency.
    chance: 0.03
    minHeight: 10
    maxHeight: 55
    distance: 140
    twistXZ: { randFactor: 5 }
    scaleY: { startVal: 4 }
    angleXZ: { startValRandFactor: 1.5 }
    angleY: { startValRandFactor: 0.75 }
    scale: {
      startVal: 2
      startValRandFactor: 2
    }
    noiseYFactor: 0.9
     # Use a noise generator to handle wall shape.
    wallNoise: {
      noise2D: {
        frequency: 0.1
        minVal: 0
        maxVal: 4
      }
    }
  }
  caveBlocks: [
    { states: "lava", maxHeight: 10 }
  ]
}_

I use this preset , but always found huge ravines cut the plain over 63 block

**Comment by PersonTheCat** [comment]
That sounds right. The problem with this value is that it doesn't represent the literal maximum or minimum possible height of the tunnels, but rather the maximum or minimum *starting height*. The real height range observed is startingHeight +- tunnelRadius. It seems like a better idea to me to just document this better and continue allowing authors to account for it. 
Hope that helps!

**Comment by zzzqh** [comment]
Oh, I see , So I need to set a low value for maxHeight and reduce twistY/angleY ?

**Comment by PersonTheCat** [comment]
Yeah, that should be right.
