### ISSUE TITLE
Game frozen when generate a new world

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#5]
Have delated config file, kept only one mod and updated forge version ,but nothing change.

Game frozen when generate world at around 90% to 99%

**Comment by PersonTheCat** [comment]
Damn. Okay, I'm gonna need a little more information about your setup. Are you using any other mods? Have you tried it without other mods? I'll need to either see if any might be interacting or at least send you a debug build, if not.

**Comment by zzzqh** [comment]
Not other mod, just this mod in version 0.4

**Comment by PersonTheCat** [comment]
Hm. I'm really not sure about this one. It is working for me. What is your operating system? Are you using the vanilla.json preset or a different one?

**Comment by zzzqh** [comment]
Windows 7 and java 1.8.10_181. With only vanilla.json. I can enter game only after delete all json in preset fold

**Comment by PersonTheCat** [comment]
Okay, then. I still can't imagine what the issue would be. Give me until tomorrow to write a debug version for you. That'll tell me where it's getting frozen.

**Comment by zzzqh** [comment]
Thanks!

**Comment by PersonTheCat** [comment]
Okay. This will generate a very large log file. Stop the game as soon as nothing is happening or it's obviously as far as it will get. I need both (fml-junk-earlystartup.log) and (latest.log OR fml-client-latest.log, whichever is larger and newer). If you can't send me the whole file, just send as much of the end as you can.

Sorry if this is too much trouble. :( There's no other way for me to know how this is happening. Thanks for your help! 

[cavegenerator-0.4.2.zip](https://github.com/PersonTheCat/CaveGenerator/files/2258481/cavegenerator-0.4.2.zip)

**Comment by zzzqh** [comment]
No problem, here is the log file.

https://1drv.ms/u/s!AmwogjsdYCKmhVHUl0J34RcywmFs

**Comment by PersonTheCat** [comment]
Thanks. This showed me exactly what went wrong. The mod tries to record some data to the disk, but it was taking too long. Because that prevented the game from shutting down, it kept retrying, creating a very slow, infinite loop. Please try this newest version and let me know if it fixes the problem for you. 

[cavegenerator-0.4.3.zip](https://github.com/PersonTheCat/CaveGenerator/files/2259726/cavegenerator-0.4.3.zip)

**Comment by zzzqh** [comment]
yes,it works well now, thanks!

**Comment by PersonTheCat** [comment]
Awesome! Thanks for your help. I'll release this right away.

**Comment by zzzqh** [comment]
wait...it seems still have some problem, I quit the game right now and it frozen again when saving world.
