### ISSUE TITLE
Game frozen when saving world

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#7]
Again, not other mod, game frozen when quit and saving world, version 0.5

**Comment by PersonTheCat** [comment]
Thanks again. Unfortunately, I've spaced these events out as much as I know how. What this ultimately comes down to is HDD write speeds. I'm still looking into better ways to handle the issue, but if I can't find anything, I'll at least put an option in the config file to disable the feature. I'll let you know!

**Comment by zzzqh** [comment]
Thank you! waiting for good news.

**Comment by PersonTheCat** [comment]
Okay. I've been working pretty hard on this one. I just want to let you know, I've completely removed the need to save any data to the disk. That should workaround this issue. The update will be out soon. Let me know if everything is working for you again!

**Comment by zzzqh** [comment]
Thank you so much! it works very well for me, no longer frozen now.
